export enum PaymentMutationTypes {
  SET_PAYMENT_ID = 'SET_PAYMENT_ID',
  SET_SHOW_PAYMENT = 'SET_SHOW_PAYMENT',
  SET_PAY_DATA = 'SET_PAY_DATA',
  SET_PAY_TYPE = 'SET_PAY_TYPE',
  SET_RESOLVE = 'SET_RESOLVE',
  SET_REJECT = 'SET_REJECT',
  SET_ALL = 'SET_ALL',
}
