export enum MallConfigActionTypes {
  ACTION_MALL_GET_CONFIG = 'ACTION_MALL_GET_CONFIG',
  ACTION_MALL_MUT_HEIGHT = 'ACTION_MALL_MUT_HEIGHT',
  ACTION_MALL_RESET_CONFIG = 'ACTION_MALL_RESET_CONFIG',
}
