export type goodsType = {
  id: string
  thumb: string
  productName: string
  marketPrice: number
  minprice?: number
  prevPrice?: number
  level_price?: number
  price_member_min?: number
  price_member_max?: number
  sliderImage?: string[]
  content?: string
  skus?: any[]
  attrGroups?: any[]
  attr?: any[]
  originalPrice?: string
  salesNum?: string
  cats?: string[]
  curriculum_content?: any[]
  curriculum_datetime?: any[]
  curriculum_type?: number
  curriculum_address?: string
  teacherNames?: string
  curriculum_start_time?: string
  curriculum_end_time?: string
  sales?: number
  subtitle?: string
  favorite?: boolean
  level_show?: number
  sell_time?: number
  is_time?: number
}
