export enum CartMutationTypes {
  SET_SELECTED_CART_GOODS = 'SET_SELECTED_CART_GOODS',
  SET_PREVIEW_ORDER_PARAM = 'SET_PREVIEW_ORDER_PARAM',
  SET_ORDER_SUBMIT_FROM_DATA = 'SET_ORDER_SUBMIT_FROM_DATA',
}
